// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: options/gorm.proto

/*
Package gorm is a generated protocol buffer package.

It is generated from these files:
	options/gorm.proto

It has these top-level messages:
	GormFileOptions
	GormMessageOptions
	ExtraField
	GormFieldOptions
	GormTag
	HasOneOptions
	BelongsToOptions
	HasManyOptions
	ManyToManyOptions
	AutoServerOptions
	MethodOptions
*/
package gorm

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type GormFileOptions struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GormFileOptions) Reset()                    { *m = GormFileOptions{} }
func (m *GormFileOptions) String() string            { return proto.CompactTextString(m) }
func (*GormFileOptions) ProtoMessage()               {}
func (*GormFileOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{0} }

type GormMessageOptions struct {
	Ormable          *bool         `protobuf:"varint,1,req,name=ormable" json:"ormable,omitempty"`
	Include          []*ExtraField `protobuf:"bytes,2,rep,name=include" json:"include,omitempty"`
	Table            *string       `protobuf:"bytes,3,opt,name=table" json:"table,omitempty"`
	MultiAccount     *bool         `protobuf:"varint,4,opt,name=multi_account,json=multiAccount" json:"multi_account,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *GormMessageOptions) Reset()                    { *m = GormMessageOptions{} }
func (m *GormMessageOptions) String() string            { return proto.CompactTextString(m) }
func (*GormMessageOptions) ProtoMessage()               {}
func (*GormMessageOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{1} }

func (m *GormMessageOptions) GetOrmable() bool {
	if m != nil && m.Ormable != nil {
		return *m.Ormable
	}
	return false
}

func (m *GormMessageOptions) GetInclude() []*ExtraField {
	if m != nil {
		return m.Include
	}
	return nil
}

func (m *GormMessageOptions) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *GormMessageOptions) GetMultiAccount() bool {
	if m != nil && m.MultiAccount != nil {
		return *m.MultiAccount
	}
	return false
}

type ExtraField struct {
	Type             *string  `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	Name             *string  `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Tag              *GormTag `protobuf:"bytes,3,opt,name=tag" json:"tag,omitempty"`
	Package          *string  `protobuf:"bytes,4,opt,name=package" json:"package,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ExtraField) Reset()                    { *m = ExtraField{} }
func (m *ExtraField) String() string            { return proto.CompactTextString(m) }
func (*ExtraField) ProtoMessage()               {}
func (*ExtraField) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{2} }

func (m *ExtraField) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *ExtraField) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ExtraField) GetTag() *GormTag {
	if m != nil {
		return m.Tag
	}
	return nil
}

func (m *ExtraField) GetPackage() string {
	if m != nil && m.Package != nil {
		return *m.Package
	}
	return ""
}

type GormFieldOptions struct {
	Tag  *GormTag `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
	Drop *bool    `protobuf:"varint,2,opt,name=drop" json:"drop,omitempty"`
	// Types that are valid to be assigned to Association:
	//	*GormFieldOptions_HasOne
	//	*GormFieldOptions_BelongsTo
	//	*GormFieldOptions_HasMany
	//	*GormFieldOptions_ManyToMany
	Association      isGormFieldOptions_Association `protobuf_oneof:"association"`
	ReferenceOf      *string                        `protobuf:"bytes,7,opt,name=reference_of,json=referenceOf" json:"reference_of,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *GormFieldOptions) Reset()                    { *m = GormFieldOptions{} }
func (m *GormFieldOptions) String() string            { return proto.CompactTextString(m) }
func (*GormFieldOptions) ProtoMessage()               {}
func (*GormFieldOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{3} }

type isGormFieldOptions_Association interface {
	isGormFieldOptions_Association()
}

type GormFieldOptions_HasOne struct {
	HasOne *HasOneOptions `protobuf:"bytes,3,opt,name=has_one,json=hasOne,oneof"`
}
type GormFieldOptions_BelongsTo struct {
	BelongsTo *BelongsToOptions `protobuf:"bytes,4,opt,name=belongs_to,json=belongsTo,oneof"`
}
type GormFieldOptions_HasMany struct {
	HasMany *HasManyOptions `protobuf:"bytes,5,opt,name=has_many,json=hasMany,oneof"`
}
type GormFieldOptions_ManyToMany struct {
	ManyToMany *ManyToManyOptions `protobuf:"bytes,6,opt,name=many_to_many,json=manyToMany,oneof"`
}

func (*GormFieldOptions_HasOne) isGormFieldOptions_Association()     {}
func (*GormFieldOptions_BelongsTo) isGormFieldOptions_Association()  {}
func (*GormFieldOptions_HasMany) isGormFieldOptions_Association()    {}
func (*GormFieldOptions_ManyToMany) isGormFieldOptions_Association() {}

func (m *GormFieldOptions) GetAssociation() isGormFieldOptions_Association {
	if m != nil {
		return m.Association
	}
	return nil
}

func (m *GormFieldOptions) GetTag() *GormTag {
	if m != nil {
		return m.Tag
	}
	return nil
}

func (m *GormFieldOptions) GetDrop() bool {
	if m != nil && m.Drop != nil {
		return *m.Drop
	}
	return false
}

func (m *GormFieldOptions) GetHasOne() *HasOneOptions {
	if x, ok := m.GetAssociation().(*GormFieldOptions_HasOne); ok {
		return x.HasOne
	}
	return nil
}

func (m *GormFieldOptions) GetBelongsTo() *BelongsToOptions {
	if x, ok := m.GetAssociation().(*GormFieldOptions_BelongsTo); ok {
		return x.BelongsTo
	}
	return nil
}

func (m *GormFieldOptions) GetHasMany() *HasManyOptions {
	if x, ok := m.GetAssociation().(*GormFieldOptions_HasMany); ok {
		return x.HasMany
	}
	return nil
}

func (m *GormFieldOptions) GetManyToMany() *ManyToManyOptions {
	if x, ok := m.GetAssociation().(*GormFieldOptions_ManyToMany); ok {
		return x.ManyToMany
	}
	return nil
}

func (m *GormFieldOptions) GetReferenceOf() string {
	if m != nil && m.ReferenceOf != nil {
		return *m.ReferenceOf
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GormFieldOptions) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GormFieldOptions_OneofMarshaler, _GormFieldOptions_OneofUnmarshaler, _GormFieldOptions_OneofSizer, []interface{}{
		(*GormFieldOptions_HasOne)(nil),
		(*GormFieldOptions_BelongsTo)(nil),
		(*GormFieldOptions_HasMany)(nil),
		(*GormFieldOptions_ManyToMany)(nil),
	}
}

func _GormFieldOptions_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GormFieldOptions)
	// association
	switch x := m.Association.(type) {
	case *GormFieldOptions_HasOne:
		_ = b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HasOne); err != nil {
			return err
		}
	case *GormFieldOptions_BelongsTo:
		_ = b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BelongsTo); err != nil {
			return err
		}
	case *GormFieldOptions_HasMany:
		_ = b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HasMany); err != nil {
			return err
		}
	case *GormFieldOptions_ManyToMany:
		_ = b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ManyToMany); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("GormFieldOptions.Association has unexpected type %T", x)
	}
	return nil
}

func _GormFieldOptions_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GormFieldOptions)
	switch tag {
	case 3: // association.has_one
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HasOneOptions)
		err := b.DecodeMessage(msg)
		m.Association = &GormFieldOptions_HasOne{msg}
		return true, err
	case 4: // association.belongs_to
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BelongsToOptions)
		err := b.DecodeMessage(msg)
		m.Association = &GormFieldOptions_BelongsTo{msg}
		return true, err
	case 5: // association.has_many
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HasManyOptions)
		err := b.DecodeMessage(msg)
		m.Association = &GormFieldOptions_HasMany{msg}
		return true, err
	case 6: // association.many_to_many
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ManyToManyOptions)
		err := b.DecodeMessage(msg)
		m.Association = &GormFieldOptions_ManyToMany{msg}
		return true, err
	default:
		return false, nil
	}
}

func _GormFieldOptions_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GormFieldOptions)
	// association
	switch x := m.Association.(type) {
	case *GormFieldOptions_HasOne:
		s := proto.Size(x.HasOne)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GormFieldOptions_BelongsTo:
		s := proto.Size(x.BelongsTo)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GormFieldOptions_HasMany:
		s := proto.Size(x.HasMany)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GormFieldOptions_ManyToMany:
		s := proto.Size(x.ManyToMany)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GormTag struct {
	Column                         *string `protobuf:"bytes,1,opt,name=column" json:"column,omitempty"`
	Type                           *string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Size_                          *int32  `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	Precision                      *int32  `protobuf:"varint,4,opt,name=precision" json:"precision,omitempty"`
	PrimaryKey                     *bool   `protobuf:"varint,5,opt,name=primary_key,json=primaryKey" json:"primary_key,omitempty"`
	Unique                         *bool   `protobuf:"varint,6,opt,name=unique" json:"unique,omitempty"`
	Default                        *string `protobuf:"bytes,7,opt,name=default" json:"default,omitempty"`
	NotNull                        *bool   `protobuf:"varint,8,opt,name=not_null,json=notNull" json:"not_null,omitempty"`
	AutoIncrement                  *bool   `protobuf:"varint,9,opt,name=auto_increment,json=autoIncrement" json:"auto_increment,omitempty"`
	Index                          *string `protobuf:"bytes,10,opt,name=index" json:"index,omitempty"`
	UniqueIndex                    *string `protobuf:"bytes,11,opt,name=unique_index,json=uniqueIndex" json:"unique_index,omitempty"`
	Embedded                       *bool   `protobuf:"varint,12,opt,name=embedded" json:"embedded,omitempty"`
	EmbeddedPrefix                 *string `protobuf:"bytes,13,opt,name=embedded_prefix,json=embeddedPrefix" json:"embedded_prefix,omitempty"`
	Ignore                         *bool   `protobuf:"varint,14,opt,name=ignore" json:"ignore,omitempty"`
	ForeignKey                     *string `protobuf:"bytes,15,opt,name=foreign_key,json=foreignKey" json:"foreign_key,omitempty"`
	AssociationForeignKey          *string `protobuf:"bytes,16,opt,name=association_foreign_key,json=associationForeignKey" json:"association_foreign_key,omitempty"`
	ManyToMany                     *string `protobuf:"bytes,17,opt,name=many_to_many,json=manyToMany" json:"many_to_many,omitempty"`
	JointableForeignkey            *string `protobuf:"bytes,18,opt,name=jointable_foreignkey,json=jointableForeignkey" json:"jointable_foreignkey,omitempty"`
	AssociationJointableForeignkey *string `protobuf:"bytes,19,opt,name=association_jointable_foreignkey,json=associationJointableForeignkey" json:"association_jointable_foreignkey,omitempty"`
	XXX_unrecognized               []byte  `json:"-"`
}

func (m *GormTag) Reset()                    { *m = GormTag{} }
func (m *GormTag) String() string            { return proto.CompactTextString(m) }
func (*GormTag) ProtoMessage()               {}
func (*GormTag) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{4} }

func (m *GormTag) GetColumn() string {
	if m != nil && m.Column != nil {
		return *m.Column
	}
	return ""
}

func (m *GormTag) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *GormTag) GetSize_() int32 {
	if m != nil && m.Size_ != nil {
		return *m.Size_
	}
	return 0
}

func (m *GormTag) GetPrecision() int32 {
	if m != nil && m.Precision != nil {
		return *m.Precision
	}
	return 0
}

func (m *GormTag) GetPrimaryKey() bool {
	if m != nil && m.PrimaryKey != nil {
		return *m.PrimaryKey
	}
	return false
}

func (m *GormTag) GetUnique() bool {
	if m != nil && m.Unique != nil {
		return *m.Unique
	}
	return false
}

func (m *GormTag) GetDefault() string {
	if m != nil && m.Default != nil {
		return *m.Default
	}
	return ""
}

func (m *GormTag) GetNotNull() bool {
	if m != nil && m.NotNull != nil {
		return *m.NotNull
	}
	return false
}

func (m *GormTag) GetAutoIncrement() bool {
	if m != nil && m.AutoIncrement != nil {
		return *m.AutoIncrement
	}
	return false
}

func (m *GormTag) GetIndex() string {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return ""
}

func (m *GormTag) GetUniqueIndex() string {
	if m != nil && m.UniqueIndex != nil {
		return *m.UniqueIndex
	}
	return ""
}

func (m *GormTag) GetEmbedded() bool {
	if m != nil && m.Embedded != nil {
		return *m.Embedded
	}
	return false
}

func (m *GormTag) GetEmbeddedPrefix() string {
	if m != nil && m.EmbeddedPrefix != nil {
		return *m.EmbeddedPrefix
	}
	return ""
}

func (m *GormTag) GetIgnore() bool {
	if m != nil && m.Ignore != nil {
		return *m.Ignore
	}
	return false
}

func (m *GormTag) GetForeignKey() string {
	if m != nil && m.ForeignKey != nil {
		return *m.ForeignKey
	}
	return ""
}

func (m *GormTag) GetAssociationForeignKey() string {
	if m != nil && m.AssociationForeignKey != nil {
		return *m.AssociationForeignKey
	}
	return ""
}

func (m *GormTag) GetManyToMany() string {
	if m != nil && m.ManyToMany != nil {
		return *m.ManyToMany
	}
	return ""
}

func (m *GormTag) GetJointableForeignkey() string {
	if m != nil && m.JointableForeignkey != nil {
		return *m.JointableForeignkey
	}
	return ""
}

func (m *GormTag) GetAssociationJointableForeignkey() string {
	if m != nil && m.AssociationJointableForeignkey != nil {
		return *m.AssociationJointableForeignkey
	}
	return ""
}

type HasOneOptions struct {
	Foreignkey               *string  `protobuf:"bytes,1,opt,name=foreignkey" json:"foreignkey,omitempty"`
	ForeignkeyTag            *GormTag `protobuf:"bytes,2,opt,name=foreignkey_tag,json=foreignkeyTag" json:"foreignkey_tag,omitempty"`
	AssociationForeignkey    *string  `protobuf:"bytes,3,opt,name=association_foreignkey,json=associationForeignkey" json:"association_foreignkey,omitempty"`
	AssociationAutoupdate    *string  `protobuf:"bytes,4,opt,name=association_autoupdate,json=associationAutoupdate" json:"association_autoupdate,omitempty"`
	AssociationAutocreate    *string  `protobuf:"bytes,5,opt,name=association_autocreate,json=associationAutocreate" json:"association_autocreate,omitempty"`
	AssociationSaveReference *string  `protobuf:"bytes,6,opt,name=association_save_reference,json=associationSaveReference" json:"association_save_reference,omitempty"`
	XXX_unrecognized         []byte   `json:"-"`
}

func (m *HasOneOptions) Reset()                    { *m = HasOneOptions{} }
func (m *HasOneOptions) String() string            { return proto.CompactTextString(m) }
func (*HasOneOptions) ProtoMessage()               {}
func (*HasOneOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{5} }

func (m *HasOneOptions) GetForeignkey() string {
	if m != nil && m.Foreignkey != nil {
		return *m.Foreignkey
	}
	return ""
}

func (m *HasOneOptions) GetForeignkeyTag() *GormTag {
	if m != nil {
		return m.ForeignkeyTag
	}
	return nil
}

func (m *HasOneOptions) GetAssociationForeignkey() string {
	if m != nil && m.AssociationForeignkey != nil {
		return *m.AssociationForeignkey
	}
	return ""
}

func (m *HasOneOptions) GetAssociationAutoupdate() string {
	if m != nil && m.AssociationAutoupdate != nil {
		return *m.AssociationAutoupdate
	}
	return ""
}

func (m *HasOneOptions) GetAssociationAutocreate() string {
	if m != nil && m.AssociationAutocreate != nil {
		return *m.AssociationAutocreate
	}
	return ""
}

func (m *HasOneOptions) GetAssociationSaveReference() string {
	if m != nil && m.AssociationSaveReference != nil {
		return *m.AssociationSaveReference
	}
	return ""
}

type BelongsToOptions struct {
	Foreignkey               *string  `protobuf:"bytes,1,opt,name=foreignkey" json:"foreignkey,omitempty"`
	ForeignkeyTag            *GormTag `protobuf:"bytes,2,opt,name=foreignkey_tag,json=foreignkeyTag" json:"foreignkey_tag,omitempty"`
	AssociationForeignkey    *string  `protobuf:"bytes,3,opt,name=association_foreignkey,json=associationForeignkey" json:"association_foreignkey,omitempty"`
	AssociationAutoupdate    *string  `protobuf:"bytes,4,opt,name=association_autoupdate,json=associationAutoupdate" json:"association_autoupdate,omitempty"`
	AssociationAutocreate    *string  `protobuf:"bytes,5,opt,name=association_autocreate,json=associationAutocreate" json:"association_autocreate,omitempty"`
	AssociationSaveReference *string  `protobuf:"bytes,6,opt,name=association_save_reference,json=associationSaveReference" json:"association_save_reference,omitempty"`
	XXX_unrecognized         []byte   `json:"-"`
}

func (m *BelongsToOptions) Reset()                    { *m = BelongsToOptions{} }
func (m *BelongsToOptions) String() string            { return proto.CompactTextString(m) }
func (*BelongsToOptions) ProtoMessage()               {}
func (*BelongsToOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{6} }

func (m *BelongsToOptions) GetForeignkey() string {
	if m != nil && m.Foreignkey != nil {
		return *m.Foreignkey
	}
	return ""
}

func (m *BelongsToOptions) GetForeignkeyTag() *GormTag {
	if m != nil {
		return m.ForeignkeyTag
	}
	return nil
}

func (m *BelongsToOptions) GetAssociationForeignkey() string {
	if m != nil && m.AssociationForeignkey != nil {
		return *m.AssociationForeignkey
	}
	return ""
}

func (m *BelongsToOptions) GetAssociationAutoupdate() string {
	if m != nil && m.AssociationAutoupdate != nil {
		return *m.AssociationAutoupdate
	}
	return ""
}

func (m *BelongsToOptions) GetAssociationAutocreate() string {
	if m != nil && m.AssociationAutocreate != nil {
		return *m.AssociationAutocreate
	}
	return ""
}

func (m *BelongsToOptions) GetAssociationSaveReference() string {
	if m != nil && m.AssociationSaveReference != nil {
		return *m.AssociationSaveReference
	}
	return ""
}

type HasManyOptions struct {
	Foreignkey               *string  `protobuf:"bytes,1,opt,name=foreignkey" json:"foreignkey,omitempty"`
	ForeignkeyTag            *GormTag `protobuf:"bytes,2,opt,name=foreignkey_tag,json=foreignkeyTag" json:"foreignkey_tag,omitempty"`
	AssociationForeignkey    *string  `protobuf:"bytes,3,opt,name=association_foreignkey,json=associationForeignkey" json:"association_foreignkey,omitempty"`
	PositionField            *string  `protobuf:"bytes,4,opt,name=position_field,json=positionField" json:"position_field,omitempty"`
	PositionFieldTag         *GormTag `protobuf:"bytes,5,opt,name=position_field_tag,json=positionFieldTag" json:"position_field_tag,omitempty"`
	AssociationAutoupdate    *string  `protobuf:"bytes,6,opt,name=association_autoupdate,json=associationAutoupdate" json:"association_autoupdate,omitempty"`
	AssociationAutocreate    *string  `protobuf:"bytes,7,opt,name=association_autocreate,json=associationAutocreate" json:"association_autocreate,omitempty"`
	AssociationSaveReference *string  `protobuf:"bytes,8,opt,name=association_save_reference,json=associationSaveReference" json:"association_save_reference,omitempty"`
	XXX_unrecognized         []byte   `json:"-"`
}

func (m *HasManyOptions) Reset()                    { *m = HasManyOptions{} }
func (m *HasManyOptions) String() string            { return proto.CompactTextString(m) }
func (*HasManyOptions) ProtoMessage()               {}
func (*HasManyOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{7} }

func (m *HasManyOptions) GetForeignkey() string {
	if m != nil && m.Foreignkey != nil {
		return *m.Foreignkey
	}
	return ""
}

func (m *HasManyOptions) GetForeignkeyTag() *GormTag {
	if m != nil {
		return m.ForeignkeyTag
	}
	return nil
}

func (m *HasManyOptions) GetAssociationForeignkey() string {
	if m != nil && m.AssociationForeignkey != nil {
		return *m.AssociationForeignkey
	}
	return ""
}

func (m *HasManyOptions) GetPositionField() string {
	if m != nil && m.PositionField != nil {
		return *m.PositionField
	}
	return ""
}

func (m *HasManyOptions) GetPositionFieldTag() *GormTag {
	if m != nil {
		return m.PositionFieldTag
	}
	return nil
}

func (m *HasManyOptions) GetAssociationAutoupdate() string {
	if m != nil && m.AssociationAutoupdate != nil {
		return *m.AssociationAutoupdate
	}
	return ""
}

func (m *HasManyOptions) GetAssociationAutocreate() string {
	if m != nil && m.AssociationAutocreate != nil {
		return *m.AssociationAutocreate
	}
	return ""
}

func (m *HasManyOptions) GetAssociationSaveReference() string {
	if m != nil && m.AssociationSaveReference != nil {
		return *m.AssociationSaveReference
	}
	return ""
}

type ManyToManyOptions struct {
	Jointable                      *string `protobuf:"bytes,1,opt,name=jointable" json:"jointable,omitempty"`
	Foreignkey                     *string `protobuf:"bytes,2,opt,name=foreignkey" json:"foreignkey,omitempty"`
	JointableForeignkey            *string `protobuf:"bytes,3,opt,name=jointable_foreignkey,json=jointableForeignkey" json:"jointable_foreignkey,omitempty"`
	AssociationForeignkey          *string `protobuf:"bytes,4,opt,name=association_foreignkey,json=associationForeignkey" json:"association_foreignkey,omitempty"`
	AssociationJointableForeignkey *string `protobuf:"bytes,5,opt,name=association_jointable_foreignkey,json=associationJointableForeignkey" json:"association_jointable_foreignkey,omitempty"`
	AssociationAutoupdate          *string `protobuf:"bytes,6,opt,name=association_autoupdate,json=associationAutoupdate" json:"association_autoupdate,omitempty"`
	AssociationAutocreate          *string `protobuf:"bytes,7,opt,name=association_autocreate,json=associationAutocreate" json:"association_autocreate,omitempty"`
	AssociationSaveReference       *string `protobuf:"bytes,8,opt,name=association_save_reference,json=associationSaveReference" json:"association_save_reference,omitempty"`
	XXX_unrecognized               []byte  `json:"-"`
}

func (m *ManyToManyOptions) Reset()                    { *m = ManyToManyOptions{} }
func (m *ManyToManyOptions) String() string            { return proto.CompactTextString(m) }
func (*ManyToManyOptions) ProtoMessage()               {}
func (*ManyToManyOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{8} }

func (m *ManyToManyOptions) GetJointable() string {
	if m != nil && m.Jointable != nil {
		return *m.Jointable
	}
	return ""
}

func (m *ManyToManyOptions) GetForeignkey() string {
	if m != nil && m.Foreignkey != nil {
		return *m.Foreignkey
	}
	return ""
}

func (m *ManyToManyOptions) GetJointableForeignkey() string {
	if m != nil && m.JointableForeignkey != nil {
		return *m.JointableForeignkey
	}
	return ""
}

func (m *ManyToManyOptions) GetAssociationForeignkey() string {
	if m != nil && m.AssociationForeignkey != nil {
		return *m.AssociationForeignkey
	}
	return ""
}

func (m *ManyToManyOptions) GetAssociationJointableForeignkey() string {
	if m != nil && m.AssociationJointableForeignkey != nil {
		return *m.AssociationJointableForeignkey
	}
	return ""
}

func (m *ManyToManyOptions) GetAssociationAutoupdate() string {
	if m != nil && m.AssociationAutoupdate != nil {
		return *m.AssociationAutoupdate
	}
	return ""
}

func (m *ManyToManyOptions) GetAssociationAutocreate() string {
	if m != nil && m.AssociationAutocreate != nil {
		return *m.AssociationAutocreate
	}
	return ""
}

func (m *ManyToManyOptions) GetAssociationSaveReference() string {
	if m != nil && m.AssociationSaveReference != nil {
		return *m.AssociationSaveReference
	}
	return ""
}

type AutoServerOptions struct {
	Autogen          *bool  `protobuf:"varint,1,opt,name=autogen" json:"autogen,omitempty"`
	TxnMiddleware    *bool  `protobuf:"varint,2,opt,name=txn_middleware,json=txnMiddleware" json:"txn_middleware,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *AutoServerOptions) Reset()                    { *m = AutoServerOptions{} }
func (m *AutoServerOptions) String() string            { return proto.CompactTextString(m) }
func (*AutoServerOptions) ProtoMessage()               {}
func (*AutoServerOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{9} }

func (m *AutoServerOptions) GetAutogen() bool {
	if m != nil && m.Autogen != nil {
		return *m.Autogen
	}
	return false
}

func (m *AutoServerOptions) GetTxnMiddleware() bool {
	if m != nil && m.TxnMiddleware != nil {
		return *m.TxnMiddleware
	}
	return false
}

type MethodOptions struct {
	ObjectType       *string `protobuf:"bytes,1,opt,name=object_type,json=objectType" json:"object_type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MethodOptions) Reset()                    { *m = MethodOptions{} }
func (m *MethodOptions) String() string            { return proto.CompactTextString(m) }
func (*MethodOptions) ProtoMessage()               {}
func (*MethodOptions) Descriptor() ([]byte, []int) { return fileDescriptorGorm, []int{10} }

func (m *MethodOptions) GetObjectType() string {
	if m != nil && m.ObjectType != nil {
		return *m.ObjectType
	}
	return ""
}

var E_FileOpts = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*GormFileOptions)(nil),
	Field:         52119,
	Name:          "gorm.file_opts",
	Tag:           "bytes,52119,opt,name=file_opts,json=fileOpts",
	Filename:      "options/gorm.proto",
}

var E_Opts = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*GormMessageOptions)(nil),
	Field:         52119,
	Name:          "gorm.opts",
	Tag:           "bytes,52119,opt,name=opts",
	Filename:      "options/gorm.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*GormFieldOptions)(nil),
	Field:         52119,
	Name:          "gorm.field",
	Tag:           "bytes,52119,opt,name=field",
	Filename:      "options/gorm.proto",
}

var E_Server = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.ServiceOptions)(nil),
	ExtensionType: (*AutoServerOptions)(nil),
	Field:         52119,
	Name:          "gorm.server",
	Tag:           "bytes,52119,opt,name=server",
	Filename:      "options/gorm.proto",
}

var E_Method = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MethodOptions)(nil),
	ExtensionType: (*MethodOptions)(nil),
	Field:         52119,
	Name:          "gorm.method",
	Tag:           "bytes,52119,opt,name=method",
	Filename:      "options/gorm.proto",
}

func init() {
	proto.RegisterType((*GormFileOptions)(nil), "gorm.GormFileOptions")
	proto.RegisterType((*GormMessageOptions)(nil), "gorm.GormMessageOptions")
	proto.RegisterType((*ExtraField)(nil), "gorm.ExtraField")
	proto.RegisterType((*GormFieldOptions)(nil), "gorm.GormFieldOptions")
	proto.RegisterType((*GormTag)(nil), "gorm.GormTag")
	proto.RegisterType((*HasOneOptions)(nil), "gorm.HasOneOptions")
	proto.RegisterType((*BelongsToOptions)(nil), "gorm.BelongsToOptions")
	proto.RegisterType((*HasManyOptions)(nil), "gorm.HasManyOptions")
	proto.RegisterType((*ManyToManyOptions)(nil), "gorm.ManyToManyOptions")
	proto.RegisterType((*AutoServerOptions)(nil), "gorm.AutoServerOptions")
	proto.RegisterType((*MethodOptions)(nil), "gorm.MethodOptions")
	proto.RegisterExtension(E_FileOpts)
	proto.RegisterExtension(E_Opts)
	proto.RegisterExtension(E_Field)
	proto.RegisterExtension(E_Server)
	proto.RegisterExtension(E_Method)
}

func init() { proto.RegisterFile("options/gorm.proto", fileDescriptorGorm) }

var fileDescriptorGorm = []byte{
	// 1141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xc6, 0xff, 0xeb, 0xe3, 0xd8, 0x4d, 0xa6, 0x69, 0xba, 0x44, 0x25, 0x31, 0x46, 0x15, 0x11,
	0x52, 0x1d, 0x1a, 0x95, 0x22, 0x25, 0xdc, 0x34, 0x12, 0x21, 0x05, 0x99, 0xa0, 0x69, 0xae, 0xb8,
	0x59, 0x8d, 0x77, 0xc7, 0x9b, 0x69, 0x77, 0x67, 0x96, 0xdd, 0xd9, 0x60, 0xf3, 0x08, 0xdc, 0xa3,
	0x3e, 0x05, 0x17, 0xbc, 0x05, 0x12, 0x77, 0x3c, 0x11, 0x9a, 0x99, 0xfd, 0x73, 0xec, 0x40, 0x95,
	0x2b, 0x90, 0xb8, 0x9b, 0xf3, 0xcd, 0x39, 0xdf, 0x9c, 0xf9, 0xce, 0xec, 0xf1, 0x31, 0x20, 0x11,
	0x49, 0x26, 0x78, 0x72, 0xe8, 0x8b, 0x38, 0x1c, 0x47, 0xb1, 0x90, 0x02, 0x35, 0xd5, 0x7a, 0x77,
	0xe8, 0x0b, 0xe1, 0x07, 0xf4, 0x50, 0x63, 0xd3, 0x74, 0x76, 0xe8, 0xd1, 0xc4, 0x8d, 0x59, 0x24,
	0x45, 0x6c, 0xfc, 0x46, 0x5b, 0x70, 0xef, 0x2b, 0x11, 0x87, 0x67, 0x2c, 0xa0, 0x17, 0x86, 0x65,
	0xf4, 0x4b, 0x0d, 0x90, 0xc2, 0x26, 0x34, 0x49, 0x88, 0x9f, 0xc3, 0xc8, 0x86, 0x8e, 0x88, 0x43,
	0x32, 0x0d, 0xa8, 0x5d, 0x1b, 0xd6, 0x0f, 0x2c, 0x9c, 0x9b, 0xe8, 0x13, 0xe8, 0x30, 0xee, 0x06,
	0xa9, 0x47, 0xed, 0xfa, 0xb0, 0x71, 0xd0, 0x3b, 0xda, 0x1c, 0xeb, 0x4c, 0xbe, 0x9c, 0xcb, 0x98,
	0x9c, 0x31, 0x1a, 0x78, 0x38, 0x77, 0x40, 0xdb, 0xd0, 0x92, 0x9a, 0xa3, 0x31, 0xac, 0x1d, 0x74,
	0xb1, 0x31, 0xd0, 0x47, 0xd0, 0x0f, 0xd3, 0x40, 0x32, 0x87, 0xb8, 0xae, 0x48, 0xb9, 0xb4, 0x9b,
	0xc3, 0xda, 0x81, 0x85, 0x37, 0x34, 0xf8, 0xc2, 0x60, 0x23, 0x01, 0x50, 0x32, 0x22, 0x04, 0x4d,
	0xb9, 0x88, 0x4c, 0x2e, 0x5d, 0xac, 0xd7, 0x0a, 0xe3, 0x24, 0x54, 0x59, 0x68, 0x4c, 0xad, 0xd1,
	0x3e, 0x34, 0x24, 0xf1, 0xf5, 0x71, 0xbd, 0xa3, 0xbe, 0x49, 0x4c, 0xdd, 0xee, 0x92, 0xf8, 0x58,
	0xed, 0xa8, 0x7b, 0x45, 0xc4, 0x7d, 0x43, 0x7c, 0xaa, 0x4f, 0xed, 0xe2, 0xdc, 0x1c, 0xfd, 0x59,
	0x87, 0x4d, 0x23, 0x0e, 0x0d, 0xbc, 0x5c, 0x86, 0x8c, 0xaf, 0x76, 0x2b, 0x1f, 0x82, 0xa6, 0x17,
	0x8b, 0xc8, 0xae, 0xeb, 0x2b, 0xe8, 0x35, 0x1a, 0x43, 0xe7, 0x8a, 0x24, 0x8e, 0xe0, 0x34, 0x4b,
	0xe4, 0xbe, 0x09, 0x3c, 0x27, 0xc9, 0x05, 0xcf, 0x15, 0x3e, 0x7f, 0x0f, 0xb7, 0xaf, 0x34, 0x80,
	0x3e, 0x07, 0x98, 0xd2, 0x40, 0x70, 0x3f, 0x71, 0xa4, 0xd0, 0x69, 0xf5, 0x8e, 0x76, 0x4c, 0xc8,
	0xa9, 0xc1, 0x2f, 0x45, 0x19, 0xd5, 0x9d, 0xe6, 0x18, 0x7a, 0x0a, 0x96, 0x3a, 0x28, 0x24, 0x7c,
	0x61, 0xb7, 0x74, 0xd8, 0x76, 0x71, 0xd2, 0x84, 0xf0, 0x45, 0x19, 0xa4, 0x12, 0x52, 0x08, 0x3a,
	0x81, 0x0d, 0xe5, 0xee, 0x48, 0x61, 0xc2, 0xda, 0x3a, 0xec, 0xa1, 0x09, 0x53, 0x1e, 0x97, 0x62,
	0x39, 0x12, 0xc2, 0x02, 0x44, 0x1f, 0xc2, 0x46, 0x4c, 0x67, 0x34, 0xa6, 0xdc, 0xa5, 0x8e, 0x98,
	0xd9, 0x1d, 0xad, 0x60, 0xaf, 0xc0, 0x2e, 0x66, 0xa7, 0x7d, 0xe8, 0x91, 0x24, 0x11, 0x2e, 0x23,
	0x8a, 0x60, 0xf4, 0x73, 0x0b, 0x3a, 0x99, 0x5e, 0x68, 0x07, 0xda, 0xae, 0x08, 0xd2, 0x90, 0x6b,
	0x39, 0xbb, 0x38, 0xb3, 0x8a, 0xda, 0xd6, 0x35, 0x5a, 0xd4, 0x36, 0x61, 0x3f, 0x19, 0xfd, 0x5a,
	0x58, 0xaf, 0xd1, 0x23, 0xe8, 0x46, 0x31, 0x75, 0x59, 0xc2, 0x04, 0xd7, 0x2a, 0xb5, 0x70, 0x09,
	0xa0, 0x7d, 0xe8, 0x45, 0x31, 0x0b, 0x49, 0xbc, 0x70, 0xde, 0x50, 0x23, 0x87, 0x85, 0x21, 0x83,
	0xbe, 0xa1, 0x0b, 0x75, 0x7c, 0xca, 0xd9, 0x0f, 0x29, 0xd5, 0x77, 0xb6, 0x70, 0x66, 0xa9, 0x17,
	0xe1, 0xd1, 0x19, 0x49, 0x03, 0x99, 0xdd, 0x27, 0x37, 0xd1, 0xfb, 0x60, 0x71, 0x21, 0x1d, 0x9e,
	0x06, 0x81, 0x6d, 0xe9, 0x98, 0x0e, 0x17, 0xf2, 0xdb, 0x34, 0x08, 0xd0, 0x63, 0x18, 0x90, 0x54,
	0x0a, 0x87, 0x71, 0x37, 0xa6, 0x21, 0xe5, 0xd2, 0xee, 0x6a, 0x87, 0xbe, 0x42, 0x5f, 0xe6, 0xa0,
	0x7a, 0xff, 0x8c, 0x7b, 0x74, 0x6e, 0x83, 0x79, 0xff, 0xda, 0x50, 0x32, 0x9a, 0xb3, 0x1d, 0xb3,
	0xd9, 0x33, 0x32, 0x1a, 0xec, 0xa5, 0x76, 0xd9, 0x05, 0x8b, 0x86, 0x53, 0xea, 0x79, 0xd4, 0xb3,
	0x37, 0x34, 0x73, 0x61, 0xa3, 0x8f, 0xe1, 0x5e, 0xbe, 0x76, 0xa2, 0x98, 0xce, 0xd8, 0xdc, 0xee,
	0x6b, 0x86, 0x41, 0x0e, 0x7f, 0xa7, 0x51, 0x75, 0x63, 0xe6, 0x73, 0x11, 0x53, 0x7b, 0x60, 0x6e,
	0x6c, 0x2c, 0x25, 0xd5, 0x4c, 0xc4, 0x94, 0xf9, 0x5c, 0x4b, 0x75, 0x4f, 0x07, 0x43, 0x06, 0x29,
	0xa9, 0x9e, 0xc3, 0xc3, 0x4a, 0x11, 0x9d, 0xaa, 0xf3, 0xa6, 0x76, 0x7e, 0x50, 0xd9, 0x3e, 0x2b,
	0xe3, 0x86, 0x37, 0x1e, 0xd7, 0x96, 0x61, 0xae, 0xbc, 0xa0, 0xa7, 0xb0, 0xfd, 0x5a, 0x30, 0xae,
	0xfb, 0x40, 0xce, 0xab, 0x68, 0x91, 0xf6, 0xbc, 0x5f, 0xec, 0x9d, 0x15, 0x5b, 0xe8, 0x1c, 0x86,
	0xd5, 0x64, 0xd6, 0x86, 0xdf, 0xd7, 0xe1, 0x7b, 0x15, 0xbf, 0xaf, 0x57, 0x99, 0x46, 0xbf, 0xd7,
	0xa1, 0xbf, 0xf4, 0x0d, 0xa2, 0x3d, 0x80, 0x0a, 0x4b, 0x6d, 0x49, 0x08, 0x75, 0xf6, 0x33, 0x18,
	0x94, 0x96, 0xa3, 0x3a, 0x41, 0x7d, 0x5d, 0x27, 0xe8, 0x97, 0x4e, 0xea, 0xa1, 0x7f, 0x06, 0x3b,
	0x6b, 0xe4, 0x53, 0x27, 0x34, 0x6e, 0x53, 0x4f, 0x1d, 0x76, 0x23, 0x4c, 0xbd, 0xa4, 0x34, 0xf2,
	0x88, 0xcc, 0x3b, 0x55, 0x35, 0xec, 0x45, 0xb1, 0xb9, 0x2e, 0xcc, 0x8d, 0xa9, 0x0a, 0x6b, 0xad,
	0x0d, 0x33, 0x9b, 0xe8, 0x0b, 0xd8, 0xad, 0x86, 0x25, 0xe4, 0x9a, 0x3a, 0xc5, 0x87, 0xac, 0x3f,
	0x91, 0x2e, 0xb6, 0x2b, 0x1e, 0xaf, 0xc8, 0x35, 0xc5, 0xf9, 0xfe, 0xe8, 0x8f, 0x3a, 0x6c, 0xde,
	0xec, 0x4d, 0xff, 0xab, 0x79, 0x57, 0x35, 0x7f, 0x6d, 0xc0, 0x60, 0xb9, 0x65, 0xff, 0xbb, 0xb4,
	0x7c, 0x0c, 0x83, 0x48, 0x24, 0xcc, 0xc4, 0xa8, 0x9f, 0xc7, 0x4c, 0xc3, 0x7e, 0x8e, 0x9a, 0x1f,
	0xe9, 0x13, 0x40, 0xcb, 0x6e, 0x3a, 0xaf, 0xd6, 0xba, 0xbc, 0x36, 0x97, 0x22, 0xd7, 0xa4, 0x56,
	0xa9, 0x57, 0xfb, 0x6e, 0xf5, 0xea, 0xdc, 0xbd, 0x5e, 0xd6, 0x3f, 0xd4, 0xeb, 0xb7, 0x06, 0x6c,
	0xad, 0xfc, 0x56, 0xaa, 0xdf, 0xa7, 0xa2, 0x39, 0x65, 0x15, 0x2b, 0x81, 0x1b, 0x05, 0xad, 0xaf,
	0x14, 0xf4, 0xb6, 0xce, 0xd8, 0xb8, 0xbd, 0x33, 0xde, 0x5e, 0xcd, 0xe6, 0xdf, 0x55, 0xf3, 0x5d,
	0x1a, 0x6a, 0xeb, 0x5d, 0x1a, 0xea, 0x7f, 0xaa, 0x66, 0x97, 0xb0, 0xa5, 0xb8, 0x5e, 0xd1, 0xf8,
	0x9a, 0xc6, 0x95, 0x29, 0x57, 0x9d, 0xee, 0x53, 0x33, 0x93, 0x58, 0x38, 0x37, 0xd5, 0x93, 0x97,
	0x73, 0xee, 0x84, 0xcc, 0xf3, 0x02, 0xfa, 0x23, 0x89, 0x69, 0x36, 0xe1, 0xf5, 0xe5, 0x9c, 0x4f,
	0x0a, 0x70, 0xf4, 0x29, 0xf4, 0x27, 0x54, 0x5e, 0x89, 0xca, 0xc0, 0xd8, 0x13, 0xd3, 0xd7, 0xd4,
	0x95, 0x4e, 0x36, 0xaf, 0xea, 0x3a, 0x1b, 0xe8, 0x72, 0x11, 0xd1, 0x63, 0x0c, 0xdd, 0x19, 0x0b,
	0xa8, 0x23, 0x22, 0x99, 0xa0, 0x47, 0x63, 0x33, 0xb2, 0x8f, 0xf3, 0x91, 0x7d, 0x5c, 0x19, 0xcd,
	0xed, 0xb7, 0x6f, 0xcd, 0xf8, 0xf8, 0xa0, 0xfc, 0x76, 0x2a, 0xdb, 0xd8, 0x9a, 0x19, 0x23, 0x39,
	0xbe, 0x80, 0xa6, 0xa6, 0xdb, 0x5f, 0xa1, 0x5b, 0x9e, 0xea, 0x0b, 0x46, 0xbb, 0x64, 0x5c, 0xf6,
	0xc0, 0x9a, 0xe8, 0x78, 0x02, 0x2d, 0xfd, 0x01, 0xa3, 0x0f, 0xd6, 0x24, 0x58, 0x8e, 0xc7, 0x05,
	0xdf, 0x4e, 0x35, 0xc3, 0x72, 0x1f, 0x1b, 0x96, 0x63, 0x0c, 0xed, 0x44, 0xeb, 0xbe, 0x26, 0x43,
	0x55, 0x10, 0xe6, 0xae, 0x64, 0x98, 0x4d, 0xa4, 0x2b, 0x25, 0xc3, 0x19, 0xd3, 0xf1, 0x04, 0xda,
	0xa1, 0x56, 0x1e, 0xed, 0xad, 0xb9, 0x75, 0xa5, 0x24, 0x05, 0x65, 0x36, 0x85, 0x2f, 0x6d, 0xe2,
	0x8c, 0xe4, 0xf4, 0xf9, 0xf7, 0xcf, 0x7c, 0x26, 0xaf, 0xd2, 0xe9, 0xd8, 0x15, 0xe1, 0x21, 0xe3,
	0x33, 0x31, 0x0d, 0xc4, 0x5c, 0x44, 0x94, 0x9b, 0xbf, 0x53, 0xee, 0x13, 0x9f, 0xf2, 0x27, 0x8a,
	0xe0, 0x30, 0xfb, 0xff, 0x75, 0xa2, 0x8c, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x68, 0xae, 0xd4,
	0xd8, 0x8e, 0x0d, 0x00, 0x00,
}
